### ISSUE TITLE
Vue Deployment Warning

### ISSUE THREAD

**Issue by Eshnek** [flecs-hub/explorer#25]
I am seeing this in the console of `flecs.dev/explorer`:
```
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
```

![image](https://user-images.githubusercontent.com/89618355/207492417-3cc9771d-0974-45fd-bf2f-10813a8b5b84.png)

**Comment by SanderMertens** [comment]
Nice catch! Forgot to disable dev mode

**Comment by SanderMertens** [comment]
Fixed!
