### ISSUE TITLE
flecs script parser does not detect simple errors

### ISSUE THREAD

**Issue by LowLevelMahn** [flecs-hub/explorer#34]
started flecs explorer in browser

```
cd explorer/etc
python3 -m http.server
```

then go to line 66 in the explorer: scene.flecs and change `Position3` to `Position3A` - lights will get removed - no parsing error
now remove the next openingn `{` and the parser will give you `unresolved Position3A`
and even after changing the `Position3A` back to  `Position3` you will still get the `unresolved Position3A` error when introducing other invalid changes
you can also change the numbers into total invalid double values of Position3 or Box like `xy12.32gb` without getting any parsing errors

**Comment by SanderMertens** [comment]
Yep I've noticed the same thing. I'll try to fix most of the issues by the next Flecs release!

**Comment by LowLevelMahn** [comment]
thanks - btw: nice project

**Comment by SanderMertens** [comment]
Fixed!
