### ISSUE TITLE
Support for Displaying EcsText at Arbitrary 3D Positions

### ISSUE THREAD

**Issue by iomeone** [flecs-hub/explorer#36]
Hi,

I noticed that the flecs_components_gui module includes a declaration for the EcsText component, and I'm wondering if it's possible to display text at arbitrary positions in a 3D scene. Specifically,  I would like to set both the position and rotation of the text using EcsPosition3 and EcsRotation3, or similar components, so that it can appear at different locations and orientations in a 3D space rendered with sokol.

- Does EcsText currently support this kind of functionality?

- If not, is there a recommended approach or future plans to integrate 3D positioning for text within flecs_components_gui?
Any guidance or advice would be greatly appreciated!

Thank you!

**Comment by SanderMertens** [comment]
Yup, that is something I'd like to be able to do with the sokol module. I've been experimenting with sokol & text rendering, but ran into some issues when trying to compile with web. Will likely pick this up again soon (as I also need it for UI dev).
